version: '3'
services:
        server_get:
                image: 7574-tp1-server-get
                ports:
                        - "6070:6070"
                links:
                        - db
        server_post:
                image: 7574-tp1-server-post
                ports:
                        - "6060:6060"
                links:
                        - db

        db:     
                image: 7574-tp1-db
                ports:
                        - "7060:7060"
                        - "7070:7070"


