
DIGITS_FOR_FILE_NUMBER = 8
DIGITS_FOR_FILE_ID = 8

UNDERSCORE = '_'

FILE_NAME_START = 'log'

FILE_EXTENSION = '.csv'
INDEX_EXTENSION = '.csv'

STAR_POST_IN_FILE_NAME = 0
ID_POS_IN_FILE_NAME = 1
DATE_POS_IN_FILE_NAME = 2
NUM_FILE_POS_IN_FILE_NAME = 3

LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
NAME_DATE_FORMAT = '%Y-%m-%d'
